spring: 
  mail: 
    # 邮箱服务器地址
    host: smtp.sina.com 
    #用户名
    username: xiaolong_ye1@sina.com
    #密码
    password: yxl1212456   
    default-encoding: UTF-8

mail: 
  fromMail: 
    #以谁来发送邮件
    addr: xiaolong_ye1@sina.com
